name: artifacts

on:
  #push:
  workflow_dispatch:
  #--schedule:
  # - cron: '0 20 * * *'
    inputs:
        name:
          description: 'Name'
          required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: print log
        run: echo "Hello! ${{ github.event.inputs.name }}"
      - name: Run script
        run: python test_artifacts.py github.event.inputs.name
        
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: myfile.txt
